### ISSUE TITLE
kline.query not working

### ISSUE THREAD

**Issue by farhad-b** [coinexcom/coinex_perpetual_api#11]
hi.
I get the message below when I try to get kline data. 

request: 

 {      "method":"kline.query",
        "params":["DOGEUSDT",60],
        "id": 5}

response: 

{'error': {'code': 3001, 'message': 'invalid argument'},
 'id': 5,
 'result': None}

couldn't find any fix for it.

**Comment by farhad-b** [comment]
need to use '1min', '3min', '5min' etc. instead of seconds (60, 180, 300 etc.)

**Comment by fireghostea** [comment]
hi
is use this object
            {
                "method": "kline.query",
                "params": [
                            "BTCUSDT",
                    "5min"
                ],
                "id": 5
            }
but i receive same error
{"error": {"code": 3001, "message": "invalid argument"}, "result": null, "id": 5}
how you resolve this?

**Comment by farhad-b** [comment]
> hi
> is use this object
> {
> "method": "kline.query",
> "params": [
> "BTCUSDT",
> "5min"
> ],
> "id": 5
> }
> but i receive same error
> {"error": {"code": 3001, "message": "invalid argument"}, "result": null, "id": 5}
> how you resolve this?

Hi, sorry, I am using the python API now. it is much easier. you don't need to code it yourself if you know python.
